blockfrost/blockfrost-platform

Dockerfile
The latest version is failing for some reason. Pinned cargo chef release to a working version
=> chore(docker): fix cargo chef dockerfile build

.github/workflows/ci.yaml, Cargo.lock, Cargo.toml, Dockerfile, build.rs, nix/internal/unix.nix, src/cbor/fallback_decoder.rs, src/cli.rs, src/errors.rs, src/main.rs
Adding a build script to fetch the testgen-hs binary.
Part of: https://github.com/blockfrost/blockfrost-platform/issues/107
=> Build script

.github/workflows/ci.yaml, .yamlfmt.yml
Requested by @vladimirvolek in [this Slack thread](https://input-output-rnd.slack.com/archives/C07FD0DNEMQ/p1737384845048439).
@gytis-ivaskevicius agrees.
_none_
=> chore: allow _single_ empty lines in `yamlfmt`

Cargo.lock, Cargo.toml, src/icebreakers_api.rs, src/main.rs, src/server.rs, tests/common.rs, tests/endpoints_test.rs
resolves: https://github.com/blockfrost/blockfrost-platform/issues/126
=> fix: startup server and register icebreakers after

.editorconfig, Cargo.lock, Cargo.toml, src/cli.rs
Implementation of https://github.com/blockfrost/blockfrost-platform/issues/98
Depends on https://github.com/blockfrost/blockfrost-platform/pull/130
Flags:
- --init
- --config
=> CLI bootstrap #98

build.rs
Found by @mmahut in [this Slack thread](https://input-output-rnd.slack.com/archives/C07FD0DNEMQ/p1738167107960739).
After doing a `cargo build` or `cargo build --release`, and running the resulting executable directly (i.e. not with `cargo run`), it couldn’t find the `testgen-hs` executable.
Let’s unpack the `testgen-hs` archive to where the app expects it, i.e. `testgen-hs/testgen-hs` in the parent directory of our main executable.
This is also how we (will) distribute it eventually in:
* #104
=> chore: unpack `testgen-hs` next to our final executable in `build.rs`

docs/src/pages/icebreakers.mdx, docs/src/pages/index.mdx, docs/src/pages/usecases.mdx
Corrected a typo. 
Made a few minor edits for how the first three pages flow from one to the next. 
Added detail about how to find the Discord channel on the Icebreakers page.
=> proofreading and minor edits

docs/src/content/usage.md, docs/src/content/usage/cli.mdx
=> docs: remove usage

src/cli.rs
=> make 'Info' the default log level selection in the init wizard

docs/yarn.lock
fixes: https://github.com/blockfrost/blockfrost-platform/security/dependabot/11
=> chore: docs update lock

docs/src/styles.css
I haven't found a better solution.
resolves: https://github.com/blockfrost/blockfrost-platform/issues/196
=> fix: hide toc link

src/main.rs
Attempt to fix the ipv6 issues as reported via discord.
=> Attempted fix for ipv6 issue

docs/package.json, docs/src/content/get-started.mdx, docs/src/content/installation/docker.md, docs/src/content/installation/installers.mdx, docs/src/content/installation/nix.md, docs/src/content/installation/source.mdx, docs/src/content/installation/verification.md
Following a conversation with SPO, Christos Palaskas, I added a new page, verification.md, to describe how to verify that you are up and running after going through the installation process. I made some minor edits to other pages in the Installation section also.
=> Installation verification steps

src/errors.rs, src/node/connection.rs
Resolves https://github.com/blockfrost/blockfrost-platform/issues/194
=> Add timeout to NodeClient connection

src/server.rs
Fixes #234
In #234.
It’s a timing error, see this comment:
https://github.com/blockfrost/blockfrost-platform/blob/2e95fb41cdd0e77ab8c0f78ecb1a793ce446fe8d/src/server.rs#L33-L34
=> fix: set up the metrics recorder as the very first thing

src/api/tx_submit.rs
=> fix: property test of the binary/hex trasaction heuristic

CHANGELOG.md
=> chore: add a CHANGELOG entry to #243

Cargo.lock, Cargo.toml, src/node/transactions.rs
1. Update pallas commit hash to prevent i32 overflow
2. Promote some log levels so user reports will contain more info
=> Update pallas and change some logging levels

CHANGELOG.md
I forgot to add this change with the original PR.
=> More logging in submit_transaction

docs/src/app/layout.tsx, docs/src/content/faq.mdx
Removed the numbers that had appeared for each question in the FAQ. 
Made minor adjustments to the text descriptions within the layout.tsx file for consistency.
=> Removing numbers from questions in FAQ and minor edits to layout.tsx file

flake.nix, nix/devshells.nix, nix/internal/darwin.nix, nix/internal/linux-cross-arm64.nix, nix/internal/linux.nix, nix/internal/unix.nix, nix/internal/windows-nsis.nix, nix/internal/windows.nix
Resolves #262
* We need 4 linters, because each one does something different…
* I recommend to select "hide whitespace" when reviewing.
=> chore: lint Nix on CI

docs/src/content/icebreakers.mdx, docs/src/content/options.md
Docs update has been requested in the original PR adding WebSocket load-balancing:
* #263 
You can see the rendered preview of the changes here:
* https://feat-websocket-docs.blockfrost-platform.pages.dev/icebreakers
=> docs: describe the new WebSocket load balancing

README.md
=> README: link to roadmap

docs/next-env.d.ts, docs/src/content/faq.mdx, docs/src/content/usage/docker.mdx, docs/yarn.lock
Expand and reorganize FAQ page informed by Discord chats
- Mine Discord chats to capture more FAQ content
- Informed by #ask-blockfrost and #icebreakers channels 
- Restructure content into user journey categories
- Add table of contents with section links 
- Needs to be reviewed and approved by the team
=> MK-8646 Enhance FAQ

docs/src/content/faq.mdx
Follow-up to:
* #267
… which I didn’t get to review in time.
=> docs: improve FAQ accuracy

Cargo.lock, Cargo.toml
Replace existing pallas commit  hash (which doesn't exists) with an existing one.
=> Correct pallas commit hash

Cargo.toml, nix/internal/unix.nix
Part of #272
Another suggestion from @johnalotoski.
=> chore: add package description, homepage, repository to `Cargo.toml`

nix/devshells.nix, src/health_monitor.rs, src/node/connection.rs, src/node/pool_manager.rs, src/node/sync_progress.rs, src/node/transactions.rs, tests/asserts.rs
Resolves #309
In:
* #309 
* https://github.com/blockfrost/blockfrost-platform/issues/309#issuecomment-2865624664
=> fix: improve health reporting (`GET /`) during the Byron era

build.rs, docker-compose.yml, flake.lock, flake.nix
=> chore: update `cardano-node` and others to 10.4.1

Cargo.lock, Cargo.toml, tests/endpoints_test.rs
Related to (and partly alleviates):
- #347
=> chore: add 2-minute timeouts to integration tests

crates/common/src/cli.rs, crates/common/src/config.rs, crates/dolos/src/client.rs
resolves: https://github.com/blockfrost/blockfrost-platform/issues/353
=> fix: dolos CLI
