blockfrost/blockfrost-platform

- .github/workflows/oci-image.yaml
We missed that the OCI image stopped building. It was referencing `:latest` of its dependency, and it got broken by upstream.
Found by @mmahut in this [Slack thread](https://input-output-rnd.slack.com/archives/C07FD0DNEMQ/p1736714894095699).
Fixed by @gytis-ivaskevicius in PR #105.
@mmahut suggests that we build the OCI image on each commit, but only _publish_ from `main`, and this PR implements that.
_none_
> chore: build the OCI image on every push, but publish only from `main`

- flake.nix
Follow-up to: PR #110.
The user has to be in `trusted-users` for this to work, but it's also useful as a documentation/discovery tool.
As requested by @gytis-ivaskevicius.
_none_
> chore: add `nixConfig` with IOG’s binary cache to the flake

- README.md
- docs/src/pages/_meta.js
- docs/src/pages/faq.mdx
- docs/src/pages/get-started.mdx
- docs/src/pages/index.mdx
- docs/src/pages/installation/_meta.js
- docs/src/pages/installation/docker.md
- docs/src/pages/installation/nix.md
- docs/src/pages/installation/source.mdx
- docs/src/pages/usage/_meta.js
- docs/src/pages/usage/cli.mdx
- docs/src/pages/usage/docker.mdx
- docs/theme.config.tsx
Checks are failing on `main`, because `treefmt` is changing the worktree.
See https://ci.iog.io/build/6482480/nixlog/1.
#103 didn’t have Hydra checks merged into it, so it slipped through.
_none_
> chore: run `treefmt` on `main`

- .cargo/audit.toml
- Cargo.lock
- Cargo.toml
- deny.toml
- flake.lock
- flake.nix
- nix/internal/unix.nix
Currently we’re not running these anywhere in CI:
* `cargo clippy` – a general linter,
* `cargo doc` – for checking intra-doc links,
* `cargo audit` – checking for known CVEs in the RustSec Advisory Database,
* `cargo deny` – checking licensing compatibility.
I also moved `cargo test` from the package to a separate check that is run with `cargo nextest`, which has much clearer and more informative output that the built-in `cargo test`.
_none_
> chore: run Cargo checks on the Hydra CI

- docs/src/pages/index.mdx
On the first page, fixing these two typos: 
Decentraliation -> Decentralization
primarly -> primarily
> fixing two typos

- .gitignore
- Cargo.lock
- Cargo.toml
- src/cbor/fallback_decoder.rs
While preparing the installers in:
* #104 
… I have noticed that finding the `testgen-hs` helper relied on the _current directory_. It shouldn’t, because the user can run our main executable from any directory, and it should behave in the same way.
Instead, I have added `current_exe_dir`, which points to the parent directory of our executable (`/proc/self/exe` on Linux etc.).
All search paths are also absolute now.
Previously, the Nix build didn’t work – unless the current directory was correct.
I removed directory recursion, as it's not necessary, and not what the kernel usually does when looking at `PATH` – IMO, let's keep it consistent with what the users are used to.
And the same logic is used to check for the file in each directory.
I'm not checking for the version yet, this will be …
> chore: tweak how `testgen-hs` is found in runtime

- src/api/root.rs
- src/node/sync_progress.rs
As we already use https://docs.blockfrost.io/#description/errors
```json
{
"status_code": 403,
"error": "Forbidden",
"message": "Invalid project token."
}
```
It would be a good idea to unify JSON responses and consistently use snake_case.
> fix: unify json responses

- src/errors.rs
- src/node/transactions.rs
- tests/endpoints_test.rs
In this format, only the `message` field is different.
https://app.warp.dev/block/ljaRyZihLHdISXLxpU5WdD
> One step closer to same response as blockfrost

- .github/workflows/ci.yaml
- Dockerfile
- Makefile.toml
Could you guys please fix the Dockerfile?
resolves: https://github.com/blockfrost/blockfrost-platform/issues/51
https://github.com/blockfrost/blockfrost-platform/actions/runs/13032676952/job/36355369616?pr=138
```bash
cargo install --force cargo-make
```
```bash
cargo make hadolint
[cargo-make] INFO - cargo make 0.37.24
[cargo-make] INFO - 
[cargo-make] INFO - Project: blockfrost-platform
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: hadolint
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: hadolint
Dockerfile:2 DL3027 warning: Do not use apt as it is meant to be a end-user tool, use apt-get or apt-cache instead
Dockerfile:28 DL3006 warning: Always tag the version of an image explicitly
Error while executing command, exit code: 1
```
> Hadolint docker

- src/cli.rs
- src/main.rs
Implementation of https://github.com/blockfrost/blockfrost-platform/issues/133
Unfortunately, I dont think it is possible to implement --help screen whenever the application is run without configuration due to the amount of config sources. I hope that's alright?
> Minor cli improvements

- Dockerfile
- build.rs
- flake.lock
- flake.nix
- nix/internal/windows.nix
The need to do so discovered by @ginnun in:
* #90
Via commit 7e13006519bb1792de103e548e69e89f4b35062c:
> fix: patch `Arbitrary PoolMetadata` to always have 32 bytes for `pmHash`
See also the fix in the upstream:
* https://github.com/IntersectMBO/cardano-ledger/pull/4870
> chore: update `testgen-hs` to 10.1.4.1

- nix/internal/darwin-entitlements.xml
- nix/internal/darwin.nix
Resolves #152
The pre-pre-release at [michalrus/bfp-release-testing/releases/tag/0.0.1](https://github.com/michalrus/bfp-release-testing/releases/tag/0.0.1) has been updated with properly signed, and notarized DMG images.
After mounting it:
```
❯ codesign -dv --verbose=2 "$(which blockfrost-platform)"
Executable=/Volumes/Blockfrost Platform/Blockfrost Platform.app/Contents/MacOS/bundle/libexec/blockfrost-platform
Identifier=blockfrost-platform
Format=Mach-O thin (x86_64)
CodeDirectory v=20500 size=64991 flags=0x10000(runtime) hashes=2020+7 location=embedded
Signature size=8996
Authority=Developer ID Application: Input Output HK Limited (89TW38X994)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=7 Feb 2025 at 17:00:23
Info.plist=not bound …
```
> chore: notarize the DMG artifacts

- Dockerfile
- build.rs
- flake.lock
- flake.nix
- nix/internal/windows.nix
* Backported from @ginnun's:
* #90
* #157
* Let's make sure it still works on `main`.
* Related Haskell side changes (only in test case generator): [input-output-hk/testgen-hs/compare/10.1.4.1..10.1.4.2](https://github.com/input-output-hk/testgen-hs/compare/10.1.4.1..10.1.4.2).
> chore: update `testgen-hs` to 10.1.4.2

- src/api/tx_submit.rs
- src/node/transactions.rs
Relates to #19
* We want to be able to accept both binary and hex-encoded CBOR transactions (see [this Slack thread](https://input-output-rnd.slack.com/archives/C07FD0DNEMQ/p1739450796177289?thread_ts=1739378737.982579&cid=C07FD0DNEMQ)).
* See the comment near the new function for an explanation how it works.
Now, `blockfrost-platform` accepts both binary and hex-encoded CBOR transactions:
> feat: accept both binary and hex-encoded transactions (heuristically)

- docs/src/content/installation/nix.md
- docs/src/content/usage/configuration.mdx
* I noticed in the [Using Nix](https://platform.blockfrost.io/installation/nix) section, that it could be simplified by avoiding cloning of the repo.
* More controversial: I also suggested adding IOG substituters as an option to make the build (download) really fast.
* I also found that the Linux config path was the old one (`~/.config/blockfrost` instead of `~/.config/blockfrost-platform`).
> chore: simplify `nix build` in the docs

- nix/internal/curl-bash-install.sh
@mmahut found out that `bzip2` is not installed by default on the latest Fedora right after installation.
Let’s have a better error message than:
```
tar (child): bzip2: Cannot exec: No such file or directory
```
> chore: check for `bzip2` in `curl-bash-install.sh`

- src/node/pool_manager.rs
Refactoring omission (specifically on [this line](https://github.com/blockfrost/blockfrost-platform/pull/57/files#r1959597963)) in:
* #57
Before this PR, the gauge was only ever increasing, which did not reflect reality.
> fix: readd decrementing of the `cardano_node_connections` metrics gauge

- src/api/metrics.rs
- src/api/root.rs
- src/api/tx_submit.rs
- src/node/connection.rs
- src/node/pool_manager.rs
Resolves #173
Resolves #175
Originally reported as:
* #173 
This is a good explanation – https://github.com/blockfrost/blockfrost-platform/issues/173#issuecomment-2666748539:
> * This happens on machines with high load average.
> * Then `GET /` takes a significant while.
> * But the requester doesn’t wait that long, and disconnects.
> * This results in **Axum cancelling the handling future**.
> * And that’s why our code never calls `client.send_release().await` from Pallas.
> * But the connection is returned to the pool in its `impl Drop`.
> * So the next time we try to use it, it’s in incorrect state (not released), and we try to acquire, and that’s an error, which eventually results in `N2C connection no longer viable`.
I also added a few more gauges to better instrument the code, and …
> fix: never let Axum abort Ouroboros miniprotocols on HTTP client disconnect

- .github/workflows/ci.yaml
- Dockerfile
- nix/internal/darwin.nix
- nix/internal/linux.nix
- nix/internal/unix.nix
- nix/internal/windows.nix
Resolves #186
Stacked on top of #185 which should be merged first.
Archive sizes:
| Platform | Size before | Size now |
|----------|----------|----------|
| Windows | 46.4 MiB | 7.23 MiB |
| Linux | 16.7 MB | 7.07 MiB |
| macOS (ARM) | 47.9 MB | 2.73 MiB |
| macOS (Intel) | 18.7 MB | 2.88 MiB |
> chore: remove `testgen-hs` from production packages

- src/api/metrics.rs
- src/cli.rs
- src/server.rs
- tests/common.rs
- tests/endpoints_test.rs
Fixes https://github.com/blockfrost/blockfrost-platform/issues/179
**Breaking Changes**
- Replaced `--metrics` with `--no-metrics` 
- Metrics are enabled by default when running via CLI without  `--no-metrics` 
**Changes**
- `/metrics`  url is no longer handled if metrics are disabled
- HTTP calls are no longer gauged  if metrics are disabled
> breaking: Fix metrics endpoint and enable by default

- .github/workflows/oci-image.yaml
- Dockerfile
- build.rs
- docker-compose.yml
- nix/internal/darwin.nix
- nix/internal/linux.nix
- nix/internal/unix.nix
- nix/internal/windows.nix
- src/api/root.rs
- src/cli.rs
The PR is split into these 3 commits for ease of review:
* When investigating the latest release on multiple machines, it would’ve been very handy to know which Git revision each build was prepared from. After this PR, we report it both under `--version` and `GET /`.
* I also set `meta.mainProgram` on the Nix packages – I noticed warnings when using `lib.getExe` on my home server.
* And, while at it, I removed a few explicit `"blockfrost-platform"` strings – let’s reuse the name from `Cargo.toml`.
```
❯ ./result/bin/blockfrost-platform --version
blockfrost-platform 0.0.1 (c4c765a777b3575358fe53cc38e5358cb1ff773f)
```
```
❯ curl -fsSL http://0:3000 | jq .
{
"name": "blockfrost-platform",
"version": "0.0.1",
"revision": "c4c765a777b3575358fe53cc38e5358cb1ff773f",
"healthy": true, …
```
> chore: embed Git revision in the final binary (and other minor changes)

- .github/workflows/oci-image.yaml
We didn’t have this the last time, and I had to manually tag & [publish to GHCR](https://github.com/blockfrost/blockfrost-platform/pkgs/container/blockfrost-platform/355296410?tag=0.0.1).
See [this Slack thread](https://input-output-rnd.slack.com/archives/C07FD0DNEMQ/p1739466955418789?thread_ts=1739378737.982579&cid=C07FD0DNEMQ) for more context.
> chore: publish tagged OCI images on release

- docker-compose.yml
They’re quite old, I missed `docker-compose.yml` when updating these dependencies in the devshell.
> chore: update cardano-node to 10.1.4 and mithril-client to 2506.0 in `docker-compose.yml`

- .github/workflows/oci-image.yaml
- docker-compose.yml
Just a suggestion, but it’s inline with what other orgs are doing, e.g. Alpine. And a more stable experience for users that want to always have `latest`, but not necessarily bleeding edge.
If we agree to this, I’ll manually move [`latest`](https://github.com/blockfrost/blockfrost-platform/pkgs/container/blockfrost-platform/361431820?tag=latest) to point to [`0.0.1`](https://github.com/blockfrost/blockfrost-platform/pkgs/container/blockfrost-platform/355296410?tag=0.0.1) on GHCR.
> chore: rename OCI tags: `edge` is nightly, `latest` is release

- Dockerfile
You can see GHCR / GitHub Packages complaining here:
* https://github.com/blockfrost/blockfrost-platform/pkgs/container/blockfrost-platform/355296410?tag=0.0.1
* https://github.com/orgs/blockfrost/packages/container/blockfrost-platform/settings
Here's the standard for reference:
* https://github.com/opencontainers/image-spec/blob/main/annotations.md
> chore: add missing OCI `LABEL`s, as reported by GHCR

- nix/internal/curl-bash-install.sh
- nix/internal/unix.nix
Resolves #145
See #145 for the reasoning.
I tested it via [michalrus/bfp-release-testing](https://github.com/michalrus/bfp-release-testing/releases/tag/0.0.1), you can see that this [`curl-bash-install.sh` file there](https://github.com/michalrus/bfp-release-testing/releases/download/0.0.1/curl-bash-install.sh) contains the hashes:
```bash
❯ curl -fsSL https://github.com/michalrus/bfp-release-testing/releases/download/0.0.1/curl-bash-install.sh \
| grep 'expected_sha256='
expected_sha256="0b1bcd7d3479859dd927c92dccdba15e41208a14c69c752be5c8c7d621a4daac"
expected_sha256="d1dad2c70933a03342df9a92150be9c448f8b6c770ddde1381c68690e2f00d94"
expected_sha256="16a0317df3bb51d55708c5084bb8a335db99486d24061bd33611f3f24573377b"
expected_sha256="16a0317df3bb51d55708c5084bb8a335db99486d24061bd33611f3f24 …
```
> chore: add SHA-256 checksums to the Curl-Bash installer

- nix/devshells.nix
- nix/internal/unix.nix
Two small quality-of-developer-life changes. :)
It makes it harder to see important stuff when testing.
I sometimes use it for testing, perhaps it’s useful to others, and we already depend on the `cardano-node` flake which includes it.
> chore: silence a lot of peer selection spam & expose `cardano-submit-api`

- CHANGELOG.md
- src/cli.rs
- src/main.rs
- tests/common.rs
Related to #207, #206
Let’s use the `std::net::*` types for IP config.
> chore: use `std::net` types for IP configuration

- .github/workflows/release.yml
- CHANGELOG.md
- flake.nix
- nix/internal/curl-bash-install.sh
- nix/internal/linux-cross-arm64.nix
- nix/internal/unix.nix
Resolves #210
In #210.
1. Go to Hydra builds of this PR → https://ci.iog.io/jobset/blockfrost-blockfrost-platform/pullrequest-213#tabs-jobs
2. Select `archive.aarch64-linux` → https://ci.iog.io/build/6937915
3. Download on an `aarch64-linux` machine.
4. Unpack & run.
```bash
❯ uname -a
Linux nixos-vm 6.1.55 #1-NixOS SMP Sat Sep 23 09:11:13 UTC 2023 aarch64 GNU/Linux
❯ wget https://ci.iog.io/build/6937915/download/1/blockfrost-platform-0.0.1-3ab3c23-aarch64-linux.tar.bz2
❯ tar -xf blockfrost-platform-0.0.1-3ab3c23-aarch64-linux.tar.bz2
❯ file ./blockfrost-platform/exe/blockfrost-platform
./blockfrost-platform/exe/blockfrost-platform: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter ld-linux-aarch64.so.1, for GNU/Linux 3.10.0, not stripped
❯ …
```
> chore: provide `aarch64-linux` release artifacts

- .github/workflows/git-checks.yaml
- nix/internal/windows.nix
Resolves #144
In #144.
Here’s the new code-signed installer:
[blockfrost-platform-0.0.1-d9651c2-x86_64-windows.exe.zip](https://github.com/user-attachments/files/19076234/blockfrost-platform-0.0.1-d9651c2-x86_64-windows.exe.zip)
> chore: code-sign the Windows installer

- src/middlewares/metrics.rs
- src/server.rs
Resolves #220
In #220.
Additionally, I have also made the random prefix ignored in metrics.
We don’t currently use `MatchedPath`, which always matches the full prefix of a nested route. But we’ll need something better once we do.
> fix: expose `/` and `/metrics` without the UUID prefix

- src/errors.rs
- src/server.rs
Resolves https://github.com/blockfrost/blockfrost-platform/issues/225 by enriching not found error log/message.
The new message looks like: `Not Found - The requested component `/testing-enriched-not-found` has not been found for `GET` method
`
> Add more information to the not found error message/logs

- src/api/tx_submit.rs
- tests/endpoints_test.rs
resolves: https://github.com/blockfrost/blockfrost-platform/issues/230
> feat: Blockfrost response header

- CHANGELOG.md
- src/api/metrics.rs
- src/api/tx_submit.rs
- src/node/pool_manager.rs
A really minor thing, but let’s use the `counter` type for monotonic (only ever increasing) _counters_.
Gauges can go both ways – they have both `.increase()` / `.decrease()`.
It’s also a useful hint to the end user setting up a Grafana dashboard for themselves, compare:
```
cardano_node_connections_initiated 38
cardano_node_connections_failed 37
cardano_node_connections 1
```
> chore: use the `counter` type not `gauge` for monotonic metrics

- src/main.rs
Some users will inevitably give us logs for investigation, IMO, it’s good to reduce the back and forth of asking them what particular revision they’re running.
Especially since a lot of people are no longer running the latest release, but edge versions of `main`.
> chore: log the Git revision on startup

- Cargo.lock
- Cargo.toml
- src/node/transactions.rs
- tests/endpoints_test.rs
Please note that this errors are not word to word identical to the Haskell implementation. In my opinion It should be fine like this.
The specific different error message comes from the language's implementation of serializers.
Haskell:
`DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 (\"expected list len or indef\"))`
Rust:
`DecoderErrorDeserialiseFailure \"Shelley Tx\" (DeserialiseFailure 0 (\"unexpected type map at position 0: expected array\"))`
> Handle invalid tx cbors nicer in submit

- src/node/connection.rs
- src/node/pool_manager.rs
- src/node/transactions.rs
Related to #238 
On my server this happened overnight:
```
Mar 19 04:24:12 monstrum blockfrost-platform[1515427]: 2025-03-19T04:24:12.911480Z ERROR err=Error { err: Overflow(58843353900), pos: Some(705), msg: "when converting u64 to i32" }
Mar 19 04:24:12 monstrum blockfrost-platform[1515427]: 2025-03-19T04:24:12.911565Z ERROR Error occurred: Bad Request - Error during transaction submission: ChannelError(Decoding("58843353900 overflows target type at position 705: when converting u64 to i32"))
```
And each subsequent submission resulted in `AgencyIsTheirs`:
```
Mar 19 04:24:34 monstrum blockfrost-platform[1515427]: 2025-03-19T04:24:34.037194Z ERROR Error occurred: Bad Request - Error during transaction submission: AgencyIsTheirs
Mar 19 04:24:55 monstrum blockfrost-platform[1515427]: …
```
> fix: invalidate N2C connections on more serious errors

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- deny.toml
- nix/devshells.nix
- nix/internal/unix.nix
- src/server.rs
* Some SPOs already define their own Grafana dashboards.
* Also in the past we had problems with number of open FDs.
* This is cheap, and won’t hurt to have.
* The 2nd commit is just Nix noise to expose `libclang.dylib` to the builds on macOS’es.
```
❯ curl -fsSL http://0:3000/metrics | grep -E '^[a-z]' | sort
cardano_node_connections 1
cardano_node_connections_failed 0
cardano_node_connections_initiated 1
http_requests_total{method="GET",path="/metrics",status="200"} 31
process_cpu_seconds_total 0
process_max_fds 1024
process_open_fds 12
process_resident_memory_bytes 19488768
process_start_time_seconds 1742464582
process_threads 17
process_virtual_memory_bytes 1139335168
process_virtual_memory_max_bytes 0
tx_submit_failure 0
tx_submit_success 0
```
> chore: expose process metrics (memory, CPU time, fds, threads)

- docs/src/content/installation/verification.md
Follow-up to:
* #220 
* #221
@SmaugPool astutely [points out](https://discord.com/channels/826816523368005654/1283801391256698911/1353990968034070598) that we no longer need to rely on UUIDs in documentation.
That’s true, let’s get rid of them.
> fix: treat UUID as an implementation detail in docs

- Cargo.lock
- Cargo.toml
- src/cbor.rs
- src/cbor/validation.rs
- src/node/transactions.rs
- tests/endpoints_test.rs
Related to:
* #238
I wrote a [workaround](https://github.com/txpipe/pallas/commit/f74c49e409570e7835a424bd20ad0cf9e86e0efb) in pallas.
I did a workaround since a "proper fix" is going to touch lots of places. No need to put lots of effort into it, knowing that the pallas team is getting rid of the related PseudoTransactionOutput data structure.
I am also implementing pallas-validate validations. It mimics the ledger validations. But we won't use it to replace node generated validation errors. Instead, I am planning to use it to generate more errors in case of more dequeue failures.
> Update pallas & refactor cbor validation

- src/health_monitor.rs
- src/server.rs
Related to:
* #178
I need to be able to plug load balancer errors into our health response, now it’s easy, just call `.register_error_source()` from anywhere.
> chore: make it easy to plug other error sources to `GET /`

- CHANGELOG.md
- src/api/metrics.rs
- src/health_monitor.rs
* SPOs set up alerts for changes in `GET /metrics`.
* So let’s add a link between the number of health errors in `GET /` and the response in `GET /metrics`.
* After a Grafana alert for the `health_errors_total` gauge, an SPO can look at `GET /` or the logs manually.
> chore: expose a `health_errors_total` gauge in metrics

- Cargo.lock
- Cargo.toml
Resolves https://github.com/blockfrost/blockfrost-platform/issues/269
> Remove unused cbor crate dependency to fix failing build on Rust 1.86.0

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- docs/src/content/icebreakers.mdx
- docs/src/content/options.md
- src/errors.rs
- src/icebreakers_api.rs
- src/lib.rs
- src/load_balancer.rs
- src/main.rs
- src/server.rs
- tests/common.rs
- tests/endpoints_test.rs
Resolves #178
- #178
- The server-side PR (`8 files changed, 1220 insertions(+), 71 deletions(-)`) is in the second repository.
1. In non-solitary mode, when registering with the `blockfrost-icebreakers-api`, the `blockfrost-platform` gets an additional field in the successful response, with a list of load balancers to connect to:
```json
{
"route": "b0be51e5-e5fe-4e42-98a9-2246173bea19",
"load_balancers": [
{
"uri": "ws://127.0.0.1:3001/ws",
"access_token": "QNo3SYA0iPY+LfEhb2Gi5NaUOXqLw4b7ZQyg9DL4hFs="
}
]
}
```
2. Currently, this new WebSocket endpoint is served by the same IceBreakers API, because we already have it set up. So it’s easiest to run it there for the initial testing. But this part can easily be extracted, and run elsewhere, perhaps on more than one machine for redundancy. …
> feat: use a WebSocket load balancer to allow connections from behind NAT(s)

- flake.nix
- nix/nixos/blockfrost-platform.nix
- nix/nixos/default.nix
- nix/nixos/module-list.nix
Related to #272
`cardano-parts` will depend on this NixOS service definition in:
* https://github.com/input-output-hk/cardano-parts/pull/62
~~I’m not sure about the `cardano-` prefix (`cardano-blockfrost-platform`), but this is what `cardano-parts` do everywhere. Will ask @johnalotoski.~~
~~Hm, actually, they don’t to that for [`cardano-foundation/blockperf`](https://github.com/cardano-foundation/blockperf). 🤔~~
> chore: add a NixOS service for `cardano-parts`

- flake.nix
The list about missing formatters for specific file types got too large recently.
> chore: silence `treefmt` warnings

- Cargo.lock
- flake.lock
- flake.nix
- nix/devshells.nix
- nix/internal/unix.nix
Before this PR, the devshell (and Hydra) had **1.82.0**.
Slightly related to:
* #269
> chore: update `rustc` to 1.85.1 via Nixpkgs

- flake.nix
Part of #272
Suggested by @johnalotoski
After our [PR to capkgs](https://github.com/input-output-hk/capkgs/pull/4), the output there is named:
```
default-blockfrost-blockfrost-platform-0-0-2-e06029b
```
Which prevents reasonable tab completion. After this PR it will be this instead:
```
blockfrost-platform-blockfrost-blockfrost-platform-0-0-2-e06029b
```
> chore: change package name from `default` to `blockfrost-platform` for `capkgs`

- nix/devshells.nix
I noticed that jump-to-def didn’t work reliably for Rust’s standard library files.
Let’s point `rust-analyzer` to the same exact standard library that we’re building with.
> fix: set the `RUST_SRC_PATH` correctly for LSP (`rust-analyzer`) in the devshell

- flake.lock
- flake.nix
- nix/devshells.nix
- nix/internal/unix.nix
Since we're integrating Dolos (e.g. #344), it’s convenient to have it in the `devshell`.
The same derivation can be used for the Desktop app (https://github.com/blockfrost/blockfrost-platform-desktop/issues/3), and the GitHub runner (https://github.com/blockfrost/blockfrost-ops/issues/1877).
> chore: add Dolos to the devshell

- nix/internal/darwin.nix
- nix/internal/dmgbuild--tmp-mount-root.diff
This is a little cryptic, but on newer macOS, `hdiutil` mounting the DMG under `/Volumes/*` (while building it) prevents `ditto` from copying the app onto the DMG.
Unless you mount under `$TMPDIR`.
> fix: `dmgbuild` volume permissions on macOS Sonoma+

- docker-compose.yml
- flake.lock
- flake.nix
`v1.0.0-beta.0` was unable to bootstrap successfully from Mithril ([Slack thread](https://input-output-rnd.slack.com/archives/C07UAU3PRFV/p1758100026991349)).
> chore: update Dolos to `v1.0.0-beta.1`

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
This is the commit that we’ll pre-release as `0.0.3-rc.1`: 21146cad1d796a3c38caadf20325fbc7c4302e68.
I have asked Core SREs to bump this to the front of the CI queue.
I haven’t changed the version of docs, because it's only a pre-release, and we haven’t updated them to mention Dolos (logged as #383) etc.
> chore(release): 0.0.3-rc.1

- Cargo.lock
- Cargo.toml
- crates/common/Cargo.toml
- flake.lock
Errors like:
```
Crate:     fxhash
Version:   0.2.1
Warning:   unmaintained
Title:     fxhash - no longer maintained
Date:      2025-09-05
ID:        RUSTSEC-2025-0057
URL:       https://rustsec.org/advisories/RUSTSEC-2025-0057
Dependency tree:
fxhash 0.2.1
└── inquire 0.7.5
├── common 0.0.3-rc.3
│   ├── node 0.0.3-rc.3
│   │   └── blockfrost-platform 0.0.3-rc.3
│   ├── dolos 0.0.3-rc.3
│   │   └── blockfrost-platform 0.0.3-rc.3
│   └── blockfrost-platform 0.0.3-rc.3
└── blockfrost-platform 0.0.3-rc.3
```
> chore: update `advisory-db` and fix new `cargo audit` errors
